### ISSUE TITLE
Update UI for displaying data items

### ISSUE THREAD

**Issue by dr-orlovsky** [pandoraboxchain/pyrrha-boxplorer#8]
*NB: for all absent data we provide placeholder, but leave leave empty/– (N/A) fields*

## Main screen should provide the following statistics:
- total working nodes
- total cognitive jobs (active/historical)
- total reputation of the network
- total supply of PAN coins
- total data entities (kernels & datasets)
- network (Ropsten etc), with ability to switch (will require boxproxy update)
- pandora contract address (with ability to switch?)
- pandora marker contract address (with ability to switch?)
- pandora contract owner address

## WorkerNode screen should:
- contract address
- owner address
- display WorkerNode state (currentState() from contract)
- last seen online (for offline nodes)
- display active cognitive job (if there is one)
- display current reputation
- display node role (worker, verificator, arbiter): by using thresholds from stake and reputation
- display the size of the bound stake (no data yet)
- display amount of performed cognitive jobs (no data yet)
- give a history of past cognitive jobs (should be taken from ethereum blockchain, will require significant update of boxproxy + database on the server side)
- total amount of mined coins
- total reward paid by clients
- maximum historical reputation
- graphs (in future):
    - stake evolution
    - reputation evolution
    - mining rate
    - payments
    - computing load
    - time in offline

## CognitiveJob screen should:
- ...

## Data entity (Kernels & datasets) screen should:
- ...

**Comment by kostysh** [comment]
version 1.0.0 has been published to the repo.
Currently, we have just:
- lists of kernels, datasets, workers, jobs
- separate pages with detailed info

following milestones should be discussed.
